# Workbook 1: Coding practice, introducing numpy and writing your first notebook

## Overview of activities and tasks in this workbook
<div class="alert alert-block alert-info" style="color:black"> 
<ol>
    <li>The first activity this week is to refresh your python coding skills 
        by writing a simple algorithm that tries all the possible combinations of 4 digits to solve a combination lock puzzle.
        <ul>
        <li> We provide a simple class for a puzzle with methods set a problem and test whether an attempt has cracked the code.</li>
        <li> The task is to implement your algorithm in a method that can be tested using code from the problem class.</li>
        </ul>
    </li>
    <li> Having implemented your algorithm, the second activity asks you to examine it's performance as the <em>complexity</em> of the combination lock changes. <ul> 
            <li> for example, more digits, or more values per digit.</li>
            <li> The task is to use experiments and reasoning to answer a number of interactive multiple-choice questions.</li>
            <li> We provide python dictionary for you to  edit to store your answers ready for submission to the marking server.</li>
        </ul>
    </li> 
    <li> The third activity introduces the ```numpy``` class which is incredibly useful for all sorts of numeric computing.<br>
     There are some simple code cells to work through which illustrate how to: 
        <ul>
            <li> <em>slice</em> datasets into retrieve subsets of their data </li>
          <li> get statistical descriptions (e.g. mean/min/max and unique values) of numeric data </li>
          <li> Task 3 is to write a method that combines array slicing with some simple string processing to extract a set of values from a text database</li>
          <li> For those that feel confident, Task 4 is to combine code snippets from these cells to create a new method that could be used as part of a different problem<br> - evaluating an attempt to solve a Sudoku problem.</li>
    </ul></li>
    </ol>
Along the way we will refresh the idea of splitting code into different files, so code can be re-used, 
 and to keep the main code (or notebook) cleaner and more self-explanatory
    <h3>Finally you will submit your notebook to the online marking server for feedback.</h3>
    </div>

## Jupyter
If you are seeing this in your browser it means that you have successfully downloaded and run this notebook within your Jupiter environment.

You should have watched the videos that explain how a note book works, and what the different types of cells are.

If you haven't done that, on the modules blackboard go to:

**Learning materials > Getting ready for the module: setting up Jupyter**

- Please take the time to watch the video and run through the simple examples.
- it is important to understand the effect of running and re-running different cells, and the order that you do that.

**Markdown cells** such as this one, are used to display text and image files on screen. 
- markdown cells are very useful to keep a record of what you are doing, and to add notes
- they can also include html snippets to givve you more control over formatting as blue boxes illustrate


<div class="alert alert-block alert-info" style="color:black"> 
    <h3>Code in this module uses the AIenv python environment</h3>
<ul>
    <li>IF you are running the notebooks on the cloud server you need to click on the kernel menu and then change-kernel to'AIenv'.</li>
    <li>IF you are running locally AND you created a virtual environment in Jupyter<br>
        THEN click on the kernel menu then change-kernel </li>
    <li> OR in VSCode use the kernel selector in the top-right hand corner.</li>
    </ul>
</div>

## Part 1: Implementing a simple algorithm for a simple problem
### You are now ready to start doing some coding.

In the next cell:
- line 1 tells python to import one module (file) which contains details of the multiple-choice questions checking your understanding
- line 2 imports some code that lets us display multiple choice questions within a notebook
- line 3 imports the numpy library. We'll focus more on this at the end of this workbook

In [1]:
import workbook1_mcq1
from IPython.display import display
import numpy as np
import random
import traceback

## We'll start by defining classes for Problem() and CandidateSolution() 
So we can rapidly create new types of problems.

The main reason for doing this is so that algorithms know what they can call and how

<img src="figs/simple_uml.png">

In [2]:
class CandidateSolution:
    """Simple class to hold a candiate solution
    Note how this emphasises that the solution is a set of choices about
    values some variables shoul take
    """

    def __init__(self):
        self.variable_values: List = []
        self.quality: int = 0

In [3]:
class Problem:
    """generic super class we will use for problems"""

    def __init__():
        # we can't say what acceptable variable values are in general
        self.value_set = []

    def evaluate(solution: CandidateSolution) -> (int, str):
        """evaluate function
         Parameters
         ----------
        Parameters
         ----------
         attempt: list
             list of values that define a proposed solution
         Returns
         ---------
         int
             quality
             -1 means invalid,
         str
             reason why solution is invalid
             empty string if solution is ok
        """

        return -1, "evaluation function has not been defined for problem!"

### Defining a class for a combination lock problem:
<a title="Immanuel goldstein at English Wikipedia, Public domain, via Wikimedia Commons" href="https://commons.wikimedia.org/wiki/File:CombinationBikeLock.JPG"><img width="256" style="float:right" alt="CombinationBikeLock" src="https://upload.wikimedia.org/wikipedia/commons/b/b7/CombinationBikeLock.JPG"></a>

The lock has a number of **tumblers** (4 in the picture, more expensive locks have more)
- there are the same number of options for  each tumbler, typically (but not always) 10
- when the lock is made, each of the N tumblers is set with it's own specific value.
-  So in code:
   - an attempt to open the lock  
     means 
   - testing whether each of N variables has got the right value.


Coding things to note:
- This code just uses python lists to hold the answer and attempts
- I've used strict PEP8 naming conventions, docstrings and type hints for parameters to methods.  
- This is good coding practice and many github repositories will use automated checks to enforce them
- Note also I've use f-strings to create the output [Good explanation here](https://realpython.com/python-f-strings/)


In [4]:
class CombinationProblem(Problem):
    """
    Class to create simple combination lock problems
    and report whether a guess opens the lock
    """

    def __init__(self, N: int = 4, num_options: int = 10):
        """Create a new instance with a random solution
        Parameters
        ----------
        N:int
           number of tumblers
           default 4
        num_options:int
           number of possible values (positions) for each tumbler
           this version assumes they are a consecutive integers from 1 to num_options
           default 10
        """

        self.solution_length = N  # number of tumblers
        # set the allowed values in each position
        self.value_set = []
        for val in range(1, num_options + 1):
            self.value_set.append(val)

        # set  new random goal (unlock code)
        self.goal = []
        for position in range(N):
            new_random_val = random.choice(self.value_set)
            self.goal.append(new_random_val)

    def print_goal(self) -> str:
        """helper function -prints  target combinbation to screen"""
        return f"{self.goal}"

    def evaluate(self, attempt: CandidateSolution) -> (int, str):
        """
        Tests whether a provided attempt matches the combination
        Parameters
        ----------
        attempt: list
            list of values that define a proposed solution
        Returns
        ---------
        int
            quality
            -1 means  attempt is invalid, (e.g. too few or wrong values)
            0 means valid but incorrect,
            1 means correct
        str
            reason why solution is invalid
            empty string if solution is ok
        """
        #  how long is the solution?
        N = len(attempt.variable_values)
        if N is not self.solution_length:
            return -1, "attempt is wrong length"

        # is the solution made up of valid choices?
        for pos in range(N):
            if attempt.variable_values[pos] not in self.value_set:
                return -1, "error, invalid value found in solution"

        # have we found the right combination?
        if attempt.variable_values == self.goal:
            return 1, ""
        else:
            return 0, ""

<div class = "alert alert-warning" style= "color:black">
    <h2>Activity 1: Complete the skeleton code below to implement a simple algorithm to solve a combination lock puzzle</h2>
    <h3> 40 marks for correct implementation that passes a copy of  the test below on the marking server </h3>
    <p>Your code should be wrapped up as a method that can be called using the skeleton code below.<br>
    Having it as a method is neater, and means the automated marking server can test it as well.</p>
    <p> The puzzle will have 4 digits so you can hard-code the number of loops. <br>
    <b>Don't over-think this</b>: my 'reference version' only adds 8 lines of code to the skeleton</p>
    Your code should :<ol>
        <li> Take as a parameter a new puzzle instance with 4 tumblers</li>
        <li> Contain four nested for loops (one for each tumbler) 
            <ul> 
                <li>Each loop runs over all the possible values a tumbler can have.</li>
                <li> It makes your code more reusable if you do this using <br>
                    <em> for loopvar in (puzzle.value_set)</em> <br>
                  where you use a different variable name for each loop.</li></li>
            </ul>
        </li>
         <li> Inside the inner loop you need to:<ol>
             <li> Write the four values into a candidate solution</li>
             <li> pass the changed candidate solution to the puzzle's <em>evaluate()</em> method</li>
             <li> look  at the returned value and exit if you have the right combination</li>
         </ol>
        <li> Your function should return the right answer (as a list)</li>
    </ol>
    <p><b>Then run the second cell below to test your algorithm</b></p>
    <p>    <b>Hint:</b> if your 4 loop variables are called digit1, digit2, digit3, digit4<br>
        then you can set <em>attempt.variable_values = [digit1,digit2,digit3,digit4]</em></p>
    <p> <b>Note:</b>
        It's easiest to do this with four nested for loops, <br>
        but other methods might be easier to adapt to different situations.</p>
    </div>

    
    

In [5]:
def exhaustive_search_4tumblers(puzzle: CombinationProblem) -> list:
    """simple brute-force search method that tries every combination until
    it finds the answer to a 4-digit combination lock puzzle

    """

    # check that the lock has the expected number of digits
    assert puzzle.solution_length == 4, "this code only works for 4 digits"

    attempt = CandidateSolution()
    ##Your code here
    # you should have four nested for loops
    # each defining the value in a different element of attempt.variable_values
    # inside the final loop you just need four lines of code to
    # put the current values for the four loop variables into attempt.variable_values
    #   call puzzle's evaluate() method with the attempt
    #   if that returns '1',"" then return the answer stored in attempt.variable_values
    for id1 in puzzle.value_set:
        for id2 in puzzle.value_set:
            for id3 in puzzle.value_set:
                for id4 in puzzle.value_set:
                    attempt.variable_values = [id1, id2, id3, id4]
                    if puzzle.evaluate(attempt)[0] == 1:
                        return attempt.variable_values

    # should never get here
    return [-1, -1, -1, -1]

In [6]:
# run this cell to test your algorithm


def test_exhaustive_search_4tumblers():
    """function to test implementation of exhaustive search"""
    # create new puzzle
    puzzle = CombinationProblem(N=4, num_options=10)
    # call function to solve the puzzle
    # wrap it in a try...except to help debug incorrect code
    try:
        search_answer = exhaustive_search_4tumblers(puzzle)
        if search_answer == puzzle.goal:
            message = "Well done"
        else:
            message = (
                f"Something went wrong: your code returned the answer {search_answer}"
            )
            message += f" but the real answer was {puzzle.goal}"
    except Exception as e:
        message = "Something went wrong with your code.\n"
        message += "Here is the stack trace which should let you find the error\n"
        message += traceback.format_exc()
    # assertion fails and prints the message if something went wrong
    assert message == "Well done", message
    print(f" your code correctly found the solution {puzzle.goal}")


test_exhaustive_search_4tumblers()

 your code correctly found the solution [2, 9, 7, 6]


# Part 2: Analysing your algorithm's performance
## How does your algorithm behave as the complexity of the problem grows?

Use a combination of learning skills to find out answers to the questions below:
- **active learning** - experiments, 
- **theory learning** your understanding based on reasoning,
- **pragmatism** (trial-and-error)

<div class = "alert alert-warning" style= "color:black">
    <h2>Activity 2 (40 marks): Analysing your algorithm's effectiveness and efficiency</h2>
    <h3> 5 marks each for the first six questions, ten for the seventh</h3>
     <ol>
         <li> Run the next cell and answer the multiple-choice questions to check your understanding of your algorithm.</li>
         <li> Then copy the right answers in to the cell below where they are stored for automated marking.<br>
             <b> If you don't do this the marking server will record your answers as wrong.</b></li>
    </ol>
    <p>It's often a good idea to check your understanding of how the method works <b> in theory</b> against <b>observations</b>.<br> 
    So to check some of your answers you might want to add some print statements to your code.</p>
    <p><b>Remember that the marking server wants to see your method working for 4 digits</b><br>
    so  if you want to experiment with what happens if there are more or less than 4 digits,<br>
    you'll need to add a new cell to the notebook and  make a copy of the function with a different name.</p>
    </div>



In [7]:
print(
    "\nThese first three questions check how your algorithm should run with the settings provided.\n"
)
display(workbook1_mcq1.Q1)
display(workbook1_mcq1.Q2)
display(workbook1_mcq1.Q3)

print(
    "\n The next questions ask you to think about how fast the search space grows as you change the puzzle definition.\n"
)

display(workbook1_mcq1.Q4)
display(workbook1_mcq1.Q5)
display(workbook1_mcq1.Q6)
display(workbook1_mcq1.Q7)


These first three questions check how your algorithm should run with the settings provided.




 The next questions ask you to think about how fast the search space grows as you change the puzzle definition.



### Now you've worked out the answers, save them for the automatic marking server to read
For each of the variables in the dictionary below, change the value stored to  the right answer.

In [8]:
my_answer: dict = {
    "Q1": -1,  # replace with  of the numbers provided as options
    "Q2": -1,  # replace with  of the numbers provided as optionsv
    "Q3": -1,  # replace with  of the numbers provided as options
    "Q4": -1,  # replace with  of the numbers provided as options
    "Q5": -1,  # replace with  of the numbers provided as options
    "Q6": -1,  # replace with  of the strings provided as options
    "Q7": "don't know",
}

In [9]:
# Run this cell to check your answers are correctly stored
workbook1_mcq1.check_submitted_answers(my_answer)

some of these answers are not correct


# Part 3: Introducing the numpy package for storing and manipulating numerical data
<img src="figs/slicing.png" style="float:right" size:300/>

## Python arrays and slicing:
Python has a **numpy** module with lots of useful code for doing math, and creating and manipulating arrays of data. 

There are **lots** of books and online resources to help you learn about numpy such as [W3schools](https://www.w3schools.com/python/numpy/default.asp), [geeksforgeeks](https://www.geeksforgeeks.org/python-numpy/) and of course you can ask specific questions if you're stuck with bits of coding on [stackoverflow](https://stackoverflow.com/questions/tagged/python)

### Finding the size of arrays
- numpy arrays are created using ```np.array()```
- numpy arrays can be:
  - 1 dimensional (like a vector) datatype= ```np.array```, or 
  - N-dimension (like a matrix or a table) datatype ```np.ndarray```
- all numpy arrays have a ```.shape``` attribute
   - either a scalar (integer) value giving the length of a 1D array
   - or an array of values holding the size of different dimension
   - for the two-dimensional array X in the example shown  
     ```X.shape= [7,5]```
     

### Slicing arrays
If we have a 2D numpy array X  we can select just parts of it - i.e. groups of rows, or columns, by "slicing".  

We specify the range of rows we want, then the range of columns using ```X[start_row: end_row, start_col: end_col]``` 
- The end_row and end_col are not included in the slice.
- If start or end are empty, then the slices goes right from the start or right to the end.
- If the start is empty and the end is negative, the slices comes from the end of the row/column.

**Example 1:** If we put the letters of my name into a 1-D array  then we can pick out what we want as shown in the cell below. 

**Example 2:** (also in the cell below) If we have all the tutors names we could pick out just one row,  or the nth letter in all their names. 

**Example 3:** if (as in the iris data -- we'll see this a lot in the next topic) X has 150 rows and 4 columns then:
- ```X.shape = [150,4]```
- ```A = X[ 0 : 50 , :]```.  A is a 2d array containing the first 50 rows, and all 4 columns.
- ```B = X[ : , 3:]```.   B is a 1D array with 150 rows and  the columns 3 and onwards (in this case, it is just the last).
- ```C = X[ 0: 2, 0:4]``` C is a 2D array with 3 rows and 4 columns.

In [10]:
import numpy as np

# Example 1
print("Declaring a 1d array")
jims_name = np.array(["j", "i", "m", " ", "s", "m", "i", "t", "h"])

print(f"the variable jims_name is of type {type(jims_name)}")
print(f"it  has value {jims_name}\n and  shape {jims_name.shape}")
print("extracting a range of values from a 1-D array e.g. jims_name[0:3]:")
print(jims_name[0:3])

Declaring a 1d array
the variable jims_name is of type <class 'numpy.ndarray'>
it  has value ['j' 'i' 'm' ' ' 's' 'm' 'i' 't' 'h']
 and  shape (9,)
extracting a range of values from a 1-D array e.g. jims_name[0:3]:
['j' 'i' 'm']


In [11]:
# Example 2
print("\n Declaring a  a 2D array:")
tutors_names = np.array(
    [
        ["j", "i", "m", " ", " ", " ", " ", "s", "m", "i", "t", "h", " "],
        ["n", "a", "t", "h", "a", "n", " ", "d", "u", "r", "a", "n", " "],
        ["e", "l", "i", "s", "a", " ", " ", "c", "o", "v", "a", "t", "o"],
    ],
    dtype=str,
)
print(f"{tutors_names}")

print(
    f" tutors_names has shape {tutors_names.shape}\n"
    f"so if we print tutors_names.shape[0] we see it has {tutors_names.shape[0]} rows\n"
    f"and if we print tutors_names.shape[1] we see it has {tutors_names.shape[1]} columns"
)


 Declaring a  a 2D array:
[['j' 'i' 'm' ' ' ' ' ' ' ' ' 's' 'm' 'i' 't' 'h' ' ']
 ['n' 'a' 't' 'h' 'a' 'n' ' ' 'd' 'u' 'r' 'a' 'n' ' ']
 ['e' 'l' 'i' 's' 'a' ' ' ' ' 'c' 'o' 'v' 'a' 't' 'o']]
 tutors_names has shape (3, 13)
so if we print tutors_names.shape[0] we see it has 3 rows
and if we print tutors_names.shape[1] we see it has 13 columns


In [12]:
print("Extracting a  row with all its columns from a 2D array, e.g. tutors_names[1,:] ")
print(tutors_names[1, :])  # every column of the second row

print(
    "\nExtracting a range of columns from every row of a 2D array e.g., tutors_names[:,0:6]"
)
print(tutors_names[:, 0:6])

# This example uses negative index to read from the end of a slice
print("\nextracting a specific block of data from a 2D array e.g. tutors_names[2,-6]")
print(tutors_names[2, -6:])
print(
    "note how this example used negative indexing to count from the end not the start"
)

Extracting a  row with all its columns from a 2D array, e.g. tutors_names[1,:] 
['n' 'a' 't' 'h' 'a' 'n' ' ' 'd' 'u' 'r' 'a' 'n' ' ']

Extracting a range of columns from every row of a 2D array e.g., tutors_names[:,0:6]
[['j' 'i' 'm' ' ' ' ' ' ']
 ['n' 'a' 't' 'h' 'a' 'n']
 ['e' 'l' 'i' 's' 'a' ' ']]

extracting a specific block of data from a 2D array e.g. tutors_names[2,-6]
['c' 'o' 'v' 'a' 't' 'o']
note how this example used negative indexing to count from the end not the start


<div class = "alert alert-warning" style= "color:black">
<h2>Activity 3: practising numpy slicing</h2>
<h3> 10 marks for an implementation that passes the test. <br> Note that the marking server will use a different array of names.</h3>
Making use of the snippets above, write a function <em>get_names(namearray:np.ndarray)->list</em> that:
    <ul>
    <li>takes the array <em>tutors_names</em> as a parameter</li>
    <li>gets smaller array containing just the family names</li>
        <li> uses the python <em> str.join method</em> to turn each family name into a single string</li>
    <li>appends all the strings to a list</li>
    <li>returns that list containing the family names </li>
    </ul>
    <p><b> Your code should work if we test it with different arrays (as long as the family names have the same maximum length)</b></p>
        <p> <b>HINT1:</b> Like all coding (especially if the coder is something like chat-gpt), it's always a good idea to start by asking how you would test your code.<br> In this case I've given you a test function to help you make sure you've understood the requirements.    </p>    
    <p> <b>HINT2:</b> try the answers in  <a href="https://stackoverflow.com/questions/12453580/how-to-concatenate-join-items-in-a-list-to-a-single-string">this question</a> to see how to make strings out of the characters in a name.    </p>
    <p> <b>HINT3:</b> my solution has one for loop (using namearray.shape[0] to access the number of rows)<br> and 3 lines of code inside the loop.     </p>
    <p><b>HINT4:</b> If you look at the original array you'll see I've put spaces after my  and Nathan's family names</p>
    <p> Use the cell below to develop your code and the one after to test it.</p>
</div>

In [13]:
def get_names(namearray: np.ndarray) -> list:
    family_names = []
    # your code goes here

    return family_names

In [14]:
# run this cell to test your function
def test_get_names():
    """
    an example of writing a test to check code does what it should,
    building and using an error string to give more information.
    NOTE: we will test your code using different arrays, so you can't hard-code the answers!
    """
    tutors_names2 = np.array(
        [
            ["j", "i", "m", " ", " ", " ", " ", "s", "m", "i", "t", "h", " "],
            ["n", "a", "t", "h", "a", "n", " ", "d", "u", "r", "a", "n", " "],
            ["e", "l", "i", "s", "a", " ", " ", "c", "o", "v", "a", "t", "o"],
        ],
        dtype=str,
    )
    returned_value = get_names(tutors_names2)
    correct_value = ["smith ", "duran ", "covato"]
    error_msg = f"returned value {returned_value} should be {correct_value}"
    assert returned_value == correct_value, error_msg
    print("test passed")


test_get_names()

AssertionError: returned value [] should be ['smith ', 'duran ', 'covato']

## Some useful numerical functions provided for  numpy arrays

The real benefits of numpy arrays come when they hold numerical data.

Numpy provides **lots** of built-in mathematical functions, here we'll just illustrate a few that you'll use in this course

### making arrays full of zeros/ones etc
- via functions like ```np.zeros((rows,columns),datatype)```
- see [the numpy documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html) for more details

### Statistics that describe contents:mean, max and min
- if we call ```np.mean(myarray)```,  ```np.max(myarray)``` or ```np.min(myarray)``` on a 1D array we. get what you would expect
- if we call the methods on a N-Dimensional array we get results for the whole array
- but we can also get it for different dimensions by specifying what *axis* we want
- and ```np.argmax(myarray)``` or ```np.argmin(myarray)``` tell us where the biggest/smallest values are in the array

The cell below illustrates how to use these - and also a handy function ```np.reshape()``` which re-organises things 

In [15]:
# make a 1d array holding the values from 1 to 100
my_1darray = np.zeros(100, dtype=int)
for position in range(my_1darray.shape[0]):
    my_1darray[position] = position + 1

# to illustrate the point, let's shuffle the array first
np.random.shuffle(my_1darray)
print(f"The 1D-version of the array looks like this:\n{my_1darray}\n")

# now we can just 'reashape' this long array into a square
my_2darray = my_1darray.reshape(10, 10)
print(f"The 2D-version looks like this:\n{my_2darray}")

The 1D-version of the array looks like this:
[ 82  22  20  16  27  33 100  92  61  44  32  37  57  84  21  69  64  45
  25  70  28  75  68  91  46  11   2  48  96  66  41  58  76   9  80  15
  12  36  98  99  17  78   5  89  74  94  86  88  63   6  81  65  47  95
  42  38  34  77  87   8  40  93   4  49  18  53  85  83  51  79  59  19
  14  71  23  31  73  67  24  56   3  35   1  72  55  43   7  54  39  50
  62  29  90  30  13  52  60  97  10  26]

The 2D-version looks like this:
[[ 82  22  20  16  27  33 100  92  61  44]
 [ 32  37  57  84  21  69  64  45  25  70]
 [ 28  75  68  91  46  11   2  48  96  66]
 [ 41  58  76   9  80  15  12  36  98  99]
 [ 17  78   5  89  74  94  86  88  63   6]
 [ 81  65  47  95  42  38  34  77  87   8]
 [ 40  93   4  49  18  53  85  83  51  79]
 [ 59  19  14  71  23  31  73  67  24  56]
 [  3  35   1  72  55  43   7  54  39  50]
 [ 62  29  90  30  13  52  60  97  10  26]]


In [16]:
# getting the unique values in an array
uniques = np.unique(my_1darray)
print(
    f" np.unique returns an array of the different values present which are:\n{uniques}\n"
)

print(
    f"we can use the shape attribute to see there are there are {uniques.shape[0]} different values in the array"
)

 np.unique returns an array of the different values present which are:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

we can use the shape attribute to see there are there are 100 different values in the array


In [17]:
# now lets have some statistics

# 1D means and max
oneD_biggest = np.max(my_1darray)
oneD_mean = np.mean(my_1darray)
print(f" the one-D array has biggest value {oneD_biggest} and mean {oneD_mean}")

 the one-D array has biggest value 100 and mean 50.5


In [18]:
# 2d versions
twoD_biggest = np.max(my_2darray)
twoD_mean = np.mean(my_2darray)
print(f"The two-D array also has biggest value {twoD_biggest} and mean {twoD_mean}\n")

print("But we can also get row/column stats by asking min/mean to report by axes\n")
row_wise_biggest = np.max(my_2darray, axis=0)
row_wise_mean = np.mean(my_2darray, axis=0)
column_wise_biggest = np.max(my_2darray, axis=1)
column_wise_mean = np.mean(my_2darray, axis=1)

print(f"row-by-row maxima are {row_wise_biggest}")
print(f"colum-by-column means are {column_wise_mean}")

The two-D array also has biggest value 100 and mean 50.5

But we can also get row/column stats by asking min/mean to report by axes

row-by-row maxima are [ 82  93  90  95  80  94 100  97  98  99]
colum-by-column means are [49.7 50.4 53.1 52.4 60.  57.4 55.5 43.7 35.9 46.9]


In [19]:
# locations of max

location = np.argmax(my_1darray)
print(f"The biggest value is found in location {location}")

The biggest value is found in location 6


<div class = "alert alert-warning" style= "color:black">
<h2>Activity 4 : Bringing it all together in a search contex</h2>
    <h3> This is a <em>Stretch</em> activity so don't worry if you can't complete it easily    
<h3> 10 marks</h3>
    Complete the code snippet below to create a testing function for a sudoku problem.<br>
    Your code should:
    <ul>
        <li> Take a 2d numpy array <em>attempt</em> as input</li>
        <li> Use assertions to check that the array has 9 rows and 9 columns</li>
        <li> Define 27 <it>slices</it> or subarrays corresponding to the 9 sub-squares, 9 rows and 9 columns<br>
            Here are three to get you started<br>
            <em>row1 = attempt[1,:]</em><br>
            <em> col9 = attempt[,:8]<br>
                <em>top_middle_square = attempt[0:3, 3:6]</em> </li>
        <li> Store these slices in a list called <em>slices</em> </li>
        <li> Use <em>np.uniques()</em> to check that each slice has 9 unique values </li>
        <li> Return an integer saying how many of the 27 checks the attempt passes</li>
    </ul>
    <p> <b>HINTS</b> <ul>
    <li> If you don't want to define each slice by hand, (like I have started doing above), you could do it <em>programmatically</em> <br>
        i.e., by iterating over (0...8) you can define (and then add to the list) the slices for the rows and columns automatically</li>
    <li> and then add the 9 sub-square slices either by hand or using 2 nested loops</li>
    </ul>
</div>    

In [ ]:
def check_sudoku_array(attempt: np.ndarray) -> int:
    tests_passed = 0
    # your code goes here

    # use assertions to check that the array has 2 dimensions each of size 9

    slices = []  # this will be a list of numpy arrays
    # your code goes here

    ## remember all the examples of indexing above
    ## and use the append() method to add something to a list

    for slice in slices:  # easiest way to iterate over list
        pass
        # print(slice) - useful for debugging?

        # get number of unique values in slice

        # increment value of tests_passed as appropriate

    # return count of tests passed
    return tests_passed

In [ ]:
# some sample code to test your function

attempt = np.array(
    [
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [2, 3, 4, 5, 6, 7, 8, 9, 1],
        [3, 4, 5, 6, 7, 8, 9, 1, 2],
        [4, 5, 6, 7, 8, 9, 1, 2, 3],
        [5, 6, 7, 8, 9, 1, 2, 3, 4],
        [6, 7, 8, 9, 1, 2, 3, 4, 5],
        [7, 8, 9, 1, 2, 3, 4, 5, 6],
        [8, 9, 1, 2, 3, 4, 5, 6, 7],
        [9, 1, 2, 3, 4, 5, 6, 7, 8],
    ]
)

passed = check_sudoku_array(attempt)
print(passed)

<div class = "alert alert-warning" style= "color:black">
<h2>Activity 5: Submitting your work for marking</h2>
<ul> 
<li> Use the jupyterlab functions to download your work <br> 
     Ask your tutor if you need help with this <br>
     And save it somewhere sensible so you can find it easily.</li>
    <li> Then follow the links in the weekly folder in <em>Learning Materials</em> on Blackboard to submit your work for marking  and feedback.</li>
<li> You can have up to four goes at submitting your work</li>
</ul>
</div>